name: build
on: [push]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Linux setup
      run: |
        sudo apt-get install \
          tar \
          libcppunit-dev \
          autoconf \
          automake \
          autotools-dev \
          autopoint \
          libtool \
          libssl-dev \
          libssh2-1-dev \
          libc-ares-dev \
          libxml2-dev \
          zlib1g-dev \
          libsqlite3-dev \
          pkg-config
    - name: Configure autotools (Linux)
      run: |
        cd /tmp
        curl -fSL https://github.com/aria2/aria2/releases/download/release-1.36.0/aria2-1.36.0.tar.xz -o aria2.tar.xz
        tar xJf aria2.tar.xz
        cd aria2-1.36.0
        autoreconf -i
        CC="gcc"
        CXX="g++"
        ./configure \
          --with-ca-bundle='/etc/ssl/certs/ca-certificates.crt' \
          --enable-shared=no \
          ARIA2_STATIC=yes
        make
    - uses: actions/upload-artifact@v3
      with:
        name: aria2c
        path: /tmp/aria2-1.36.0/src/aria2c
